<%@ page language="java" contentType="text/cache-manifest; charset=UTF-8" pageEncoding="UTF-8"%>CACHE MANIFEST

# version=6

CACHE:
http://us.blizzard.com/_images/games/d3/bg-top.jpg
http://us.blizzard.com/_images/games/d3/bg-mid01.jpg
http://u1.sinaimg.cn/upload/h5/css/common_20111206.css
http://u1.sinaimg.cn/upload/h5/wq/js/jquery-1.5.1.min.js
http://u1.sinaimg.cn/upload/h5/css/weibov4_20120524.css
http://u1.sinaimg.cn/upload/h5/js/combine_20120525.js
http://u1.sinaimg.cn/upload/h5/js/setting_20120507.js
http://u1.sinaimg.cn/upload/2012/04/28/binding_20120428.css
http://u1.sinaimg.cn/upload/2012/04/28/binding_20120428.js
http://u1.sinaimg.cn/upload/h5/js/poi_20120523v2.js
http://u1.sinaimg.cn/upload/h5/js/lbs_20120523v2.js
http://u1.sinaimg.cn/upload/h5/css/poi_20120523.css
http://u1.sinaimg.cn/upload/h5/css/lbs_20120523.css
http://u1.sinaimg.cn/upload/h5/css/skin/pink_20120516.css
http://u1.sinaimg.cn/upload/h5/css/skin/night_20120516.css
http://u1.sinaimg.cn/upload/h5/css/skin/green_20120516.css
http://u1.sinaimg.cn/upload/h5/css/skin/gray_20120516.css 
http://u1.sinaimg.cn/upload/h5/css/skin/brown_20120516.css
http://u1.sinaimg.cn/upload/h5/css/skin/brown_20120516.css
http://u1.sinaimg.cn/upload/h5/img/app/fwall.png
http://u1.sinaimg.cn/upload/h5/img/v4/avt_def.png
http://u1.sinaimg.cn/upload/h5/img/v4/pic_default.png
http://u1.sinaimg.cn/upload/h5/img/loadimg.gif
http://u1.sinaimg.cn/upload/h5/img/v4/xbot.png
http://u1.sinaimg.cn/upload/h5/img/v4/zfbg.gif
http://u1.sinaimg.cn/upload/h5/img/v4/zfb.png
http://u1.sinaimg.cn/upload/h5/img/v4/va_xbot.jpg
http://u1.sinaimg.cn/upload/h5/img/v4/v4_xtop.jpg
http://u1.sinaimg.cn/upload/h5/img/v4/v4_top.png
http://u1.sinaimg.cn/upload/h5/img/v4/s_v4.png
http://u1.sinaimg.cn/upload/h5/img/v4/s_dv4.png
http://u1.sinaimg.cn/upload/h5/img/v4/sxne_d.png
http://u1.sinaimg.cn/upload/h5/img/v4/sxne.png
http://u1.sinaimg.cn/upload/h5/img/v4/sq_xw.png
http://u1.sinaimg.cn/upload/h5/img/v4/s.png
http://u1.sinaimg.cn/upload/h5/img/v4/msg.png
http://u1.sinaimg.cn/upload/h5/img/v4/m7.png
http://u1.sinaimg.cn/upload/h5/img/v4/m6.png
http://u1.sinaimg.cn/upload/h5/img/v4/m5.png
http://u1.sinaimg.cn/upload/h5/img/v4/m4.png
http://u1.sinaimg.cn/upload/h5/img/v4/m3.png
http://u1.sinaimg.cn/upload/h5/img/v4/m2.png
http://u1.sinaimg.cn/upload/h5/img/v4/m1.png
http://u1.sinaimg.cn/upload/h5/img/v4/logo_v4.png
http://u1.sinaimg.cn/upload/h5/img/v4/logo_dv4.png
http://u1.sinaimg.cn/upload/h5/img/v4/home_v4.png
http://u1.sinaimg.cn/upload/h5/img/v4/home_dv4.png
http://u1.sinaimg.cn/upload/h5/img/v4/g_v4.png
http://u1.sinaimg.cn/upload/h5/img/v4/g_dv4.png
http://u1.sinaimg.cn/upload/h5/img/v4/fmsg.png
http://u1.sinaimg.cn/upload/h5/img/v4/fg_v4.png
http://u1.sinaimg.cn/upload/h5/img/v4/face.png
http://u1.sinaimg.cn/upload/h5/img/v4/back_d.png
http://u1.sinaimg.cn/upload/h5/img/v4/back.png
http://u1.sinaimg.cn/upload/h5/img/app/wgame.png
http://u1.sinaimg.cn/upload/h5/img/v4/m_v4.png
http://u1.sinaimg.cn/upload/h5/img/v4/m_dv4.png
http://u1.sinaimg.cn/upload/h5/img/v4/return.png
http://u1.sinaimg.cn/upload/h5/img/main0111.png
http://u1.sinaimg.cn/upload/h5/img/rx0111.png
http://u1.sinaimg.cn/upload/h5/img/select.png
http://u1.sinaimg.cn/upload/h5/img/loading.gif
http://u1.sinaimg.cn/upload/h5/img/v4/ddb.png
http://u1.sinaimg.cn/upload/h5/img/v4/upimg.png
http://u1.sinaimg.cn/upload/h5/img/v4/db.png
http://u1.sinaimg.cn/upload/h5/img/v4/jh.png
http://u1.sinaimg.cn/upload/h5/img/v4/at.png
http://u1.sinaimg.cn/upload/h5/img/v4/ca.png
http://u1.sinaimg.cn/upload/h5/img/v4/circle.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/select_night.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/night_icon_d.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/night_icon.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/night_bg.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/mask_icon_night.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/logo_night_d.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/logo_night.png
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/loading_night_d.gif
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/loading_night.gif
http://u1.sinaimg.cn/upload/h5/img/v4/night_skin/digest_night_bg.png
http://u1.sinaimg.cn/upload/h5/img/app/kandian.png
http://u1.sinaimg.cn/upload/h5/img/app/sina_news.png
http://u1.sinaimg.cn/upload/h5/img/app/topic.png
http://u1.sinaimg.cn/upload/h5/img/app/group.png
http://u1.sinaimg.cn/upload/h5/img/app/htcmt.png
http://u1.sinaimg.cn/upload/h5/img/app/forword.png
http://u1.sinaimg.cn/upload/h5/img/app/famous.png
http://u1.sinaimg.cn/upload/h5/img/app/news.png
http://u1.sinaimg.cn/upload/h5/img/app/wbapp.png
http://u1.sinaimg.cn/upload/h5/img/app/zgame.png
http://u1.sinaimg.cn/upload/h5/img/app/wgame.png
http://u1.sinaimg.cn/upload/h5/img/app/5366.png
http://u1.sinaimg.cn/upload/h5/img/app/digest.png
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c3/zy_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8f/qq_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/89/nm_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/mb_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/17/ldln_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f3/k_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/b6/sb_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/61/sdz_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0c/sw_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/kl_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/b6/kbs_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/91/h_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/64/hs_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9c/tz_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9e/t_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/73/wq_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/e9/sk_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6a/laugh.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a6/x_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/98/yhh_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/zhh_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/5c/yw_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/yx_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7e/love.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/b8/cz_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/91/d_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/90/money_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c2/tooth.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/13/sweat.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/eb/smile.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7d/sleep_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8b/sleepy.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/05/shame_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/1a/bs_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/71/bs2_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7c/bb_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/70/88_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/57/angry.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f4/cj_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/29/bz_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/sad.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7e/hei_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/19/hate.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a4/dizzy.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/cry.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/4d/crazy.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/bd/fn_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a0/gm_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/1b/gz_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/cool_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/come_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/good_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/13/ha_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c7/no_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d6/ok_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/cc/o_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/sad_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0c/ws_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d0/z2_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/ye_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/3e/bad_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0d/right_org.gif
http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/54/left_org.gif

